package alex;

/**
 * Handles user interaction with the Alex chatbot.
 * Sends user input to the parser and returns the chatbot's response.
 */
public class Ui {

    /**
     * Processes the user's input by sending it to the parser along with the
     * current task list, storage, and aliases, and returns the chatbot's response.
     *
     * @param taskList Current list of tasks.
     * @param storage Current storage interface for tasks and aliases.
     * @param input User's input string.
     * @param aliases Current alias mappings.
     * @return Response generated by the chatbot after parsing the input.
     */
    public String run(TaskList taskList, Storage storage, String input, Alias aliases) {
        try {
            Parser p = new Parser(input);
            return p.parseInput(taskList, aliases, storage);
        } catch (AlexException e) {
            return e.getMessage();
        }
    }
}

