package james;

/**
 * Represents a response generated by James, typically used to convey
 * messages back to the user after processing a query or command, mainly built for
 * reader understandability gained compared to passing around strings
 */
public class JamesResponse {
    String message;

    /**
     * Constructs a new {@code JamesResponse} with the specified message.
     *
     * @param r The message content to be stored in the response.
     */
    public JamesResponse(String r) {
        this.message = r;
    }

    /**
     * Retrieves the message contained in this response.
     *
     * @return The response message as a {@code String}.
     */
    public String getMessage() {
        return this.message;
    }
}
