package klalopz.instructions;

import klalopz.exceptions.KlalopzException;
import klalopz.storage.DataStorage;
import klalopz.tasks.Task;
import klalopz.tasks.TaskList;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class EventInstructionTest {

    private TaskList tasks;
    private DataStorage storage;

    // For now this class's tasks are generated by AI

    @BeforeEach
    void setUp() {
        // Use a temporary storage file (won’t affect real save file)
        storage = new DataStorage(Path.of("testData.txt"));
        List<Task> temp = new ArrayList<>();
        tasks = new TaskList(temp);
    }

    @Test
    void constructor_validInput_parsesDetailsAndDate() throws Exception {
        EventInstruction instr = new EventInstruction("birthday party / 01-12-2001 / 02-12-2001");

        // using reflection only if details/dueDate are private
        // or you can add getters in EventInstruction for testing
        assertNotNull(instr);
    }
}
