package alex.command;

import java.io.IOException;

import alex.AlexException;
import alex.Alias;
import alex.CommandType;
import alex.Storage;

/**
 * Represents a command to create, view, or manage aliases for commands.
 * Handles user requests to define new aliases or display existing ones.
 */
public class AliasCommand extends TaskCommand {

    private Alias aliases;
    private Storage storage;

    /**
     * Constructs an <code>AliasCommand</code> with the provided input, aliases, and storage.
     *
     * @param inputBreakdown The user input split into command and arguments.
     * @param aliases Current alias mappings.
     * @param storage Storage interface to save updated aliases.
     */
    public AliasCommand(String[] inputBreakdown, Alias aliases, Storage storage) {
        super(inputBreakdown, null);
        this.aliases = aliases;
        this.storage = storage;
    }

    /**
     * Breaks down the task portion of the input for alias creation.
     *
     * @return Array containing the original command and its alias.
     * @throws AlexException If the user did not specify a valid alias.
     */
    public String[] taskBreakdown() throws AlexException {
        return this.getTarget("Please state which alias you would like to create").split(" ");
    }

    /**
     * Executes the alias command by either displaying existing aliases or creating a new one.
     *
     * @return Response message indicating the result of the command.
     * @throws AlexException If the input is invalid or alias creation fails.
     */
    @Override
    public String execute() throws AlexException {
        String originalWord = taskBreakdown()[0];
        CommandType command = CommandType.stringToEnum(originalWord);
        String responseMessage = "";

        if (originalWord.equals("roll")) {
            return "Here is your alias roll:\n" + aliases.listOfAliases();
        } else {
            String aliasWord = taskBreakdown()[1];
            aliases.setAlias(command, aliasWord);
            responseMessage = responseMessage + "Nice! I have added this alias:\n"
                    + command.getKeyword()
                    + ": " + aliasWord;
        }

        try {
            storage.saveAliases(aliases);
        } catch (IOException e) {
            return ("File not found. Unable to save");
        } finally {
            return responseMessage;
        }
    }

    /**
     * Returns the response generated by executing this alias command.
     *
     * @return Chatbot response after handling the alias command.
     * @throws AlexException If execution fails due to invalid input.
     */
    @Override
    public String response() throws AlexException {
        return this.execute();
    }
}
