package alex.command;

import alex.AlexException;

/**
 * Represents a command that can be executed by the Alex chatbot.
 * Implementing classes provide a response when executed.
 */
public interface Command {

    /**
     * Executes the command and returns the chatbot's response.
     *
     * @return Response generated by executing the command.
     * @throws AlexException If an error occurs during command execution.
     */
    String response() throws AlexException;
}