package alex.command;

import java.io.IOException;

import alex.AlexException;
import alex.Event;
import alex.Storage;
import alex.Task;
import alex.TaskList;

/**
 * Represents a command to add an Event task to the task list.
 * Handles parsing the user input for the event details and saving the task to storage.
 */
public class EventTaskCommand extends TaskCommand {

    private Storage storage;

    /**
     * Constructs an <code>EventTaskCommand</code> with the provided input, task list, and storage.
     *
     * @param inputBreakdown User input split into command and arguments.
     * @param taskList Current task list to add the event to.
     * @param storage Storage interface to persist tasks.
     */
    public EventTaskCommand(String[] inputBreakdown, TaskList taskList, Storage storage) {
        super(inputBreakdown, taskList);
        this.storage = storage;
    }

    /**
     * Breaks down the user input into the event description, start time, and end time.
     *
     * @return Array containing event description, start time, and end time.
     * @throws AlexException If the user input is invalid or incomplete.
     */
    public String[] taskBreakdown() throws AlexException {
        return this.getTarget("Please state when do you have the event").split(" / ");
    }

    /**
     * Executes the command by creating a new Event task, adding it to the task list,
     * and saving the updated list to storage.
     *
     * @return Confirmation message including the added task and total number of tasks.
     * @throws AlexException If the input is invalid.
     */
    @Override
    public String execute() throws AlexException {
        String eventDescription = taskBreakdown()[0];
        String eventFromTime = taskBreakdown()[1];
        String eventEndTime = taskBreakdown()[2];

        Task toAdd = new Event(eventDescription, eventFromTime, eventEndTime);
        getTaskList().add(toAdd);

        try {
            storage.saveTask(getTaskList());
        } catch (IOException e) {
            return ("File not found. Unable to save");
        } finally {
            String addTask = String.format("Ok, I've added this task: %s\n", toAdd);
            String taskLength = "Watch out, you have " + getTaskList().size() + " tasks left.";
            return addTask + taskLength;
        }
    }

    /**
     * Returns the response generated by executing this event task command.
     *
     * @return Chatbot response after adding the event task.
     * @throws AlexException If execution fails due to invalid input.
     */
    @Override
    public String response() throws AlexException {
        return this.execute();
    }
}