package alex.command;

import alex.AlexException;
import alex.TaskList;

/**
 * Represents a command to find tasks in the task list that match a given keyword.
 * Handles parsing the user's input and searching the task list.
 */
public class FindTaskCommand extends TaskCommand {

    /**
     * Constructs a <code>FindTaskCommand</code> with the provided input and task list.
     *
     * @param inputBreakdown User input split into command and arguments.
     * @param taskList Current task list to search.
     */
    public FindTaskCommand(String[] inputBreakdown, TaskList taskList) {
        super(inputBreakdown, taskList);
    }

    /**
     * Executes the command by searching for tasks containing the specified keyword.
     *
     * @return Message listing all matching tasks.
     * @throws AlexException If the input is invalid or no keyword is provided.
     */
    @Override
    public String execute() throws AlexException {
        String taskToFind = this.getTarget("Please state the item to find");
        String taskMatch = getTaskList().findMatch(taskToFind);
        String afterFind = "Here are the matching tasks in your list:\n";
        return afterFind + taskMatch;
    }

    /**
     * Returns the response generated by executing this find task command.
     *
     * @return Chatbot response listing all matching tasks.
     * @throws AlexException If execution fails due to invalid input.
     */
    @Override
    public String response() throws AlexException {
        return this.execute();
    }
}
