package alex.command;

import java.io.IOException;

import alex.AlexException;
import alex.Storage;
import alex.Task;
import alex.TaskList;
import alex.Todo;

/**
 * Represents a command to add a Todo task to the task list.
 * Handles parsing the user input and saving the task to storage.
 */
public class TodoTaskCommand extends TaskCommand {

    private Storage storage;

    /**
     * Constructs a <code>TodoTaskCommand</code> with the provided input, task list, and storage.
     *
     * @param inputBreakdown User input split into command and arguments.
     * @param taskList Current task list to add the todo to.
     * @param storage Storage interface to persist tasks.
     */
    public TodoTaskCommand(String[] inputBreakdown, TaskList taskList, Storage storage)  {
        super(inputBreakdown, taskList);
        this.storage = storage;
    }

    /**
     * Executes the command by creating a new Todo task, adding it to the task list,
     * and saving the updated list to storage.
     *
     * @return Confirmation message including the added task and total number of tasks.
     * @throws AlexException If the input is invalid or missing a task description.
     */
    @Override
    public String execute() throws AlexException {
        Task toAdd = new Todo(this.getTarget("Please state what you would like todo"));
        TaskList taskList = getTaskList();
        taskList.add(toAdd);

        try {
            storage.saveTask(taskList);
        } catch (IOException e) {
            return ("File not found. Unable to save");
        } finally {
            String addTask = String.format("Ok, I've added this task: %s\n", toAdd);
            String taskLength = "Watch out, you have " + taskList.size() + " tasks left.";
            return addTask + taskLength;
        }
    }

    /**
     * Returns the response generated by executing this todo task command.
     *
     * @return Chatbot response after adding the todo task.
     * @throws AlexException If execution fails due to invalid input.
     */
    @Override
    public String response() throws AlexException {
        return this.execute();
    }
}