package izayoi.ui;

import javafx.animation.FadeTransition;
import javafx.animation.TranslateTransition;
import javafx.scene.Node;
import javafx.util.Duration;

/**
 * Utility class to animate new chat bubbles
 * Generated by ChatGPT
 */
public class AnimationUtil {

    /**
     * Animates a new DialogBox in a popup style
     * @param node the DialogBox to be animated
     */
    public static void animateMessage(Node node) {
        // Start slightly below final position
        node.setOpacity(0);
        node.setTranslateY(20);

        // Fade-in effect
        FadeTransition fade = new FadeTransition(Duration.millis(250), node);
        fade.setFromValue(0);
        fade.setToValue(1);

        // Slide-up effect
        TranslateTransition slide = new TranslateTransition(Duration.millis(250), node);
        slide.setFromY(20);
        slide.setToY(0);

        // Play both animations together
        fade.play();
        slide.play();
    }
}
