package lux;

import lux.commands.Command;
import lux.data.AliasList;
import lux.data.TaskList;
import lux.exception.LuxException;
import lux.parser.Parser;
import lux.storage.Storage;
import lux.ui.Ui;

/**
 * Main application class that wires together UI, storage, parser and the
 * in-memory task model.
 *
 * <p>Lux is responsible for the application's lifecycle: loading persisted
 * state on startup, running the read-execute loop, and delegating input
 * parsing and command execution.
 */
public class Lux {
    private static final String DEFAULT_FILE_PATH = "data/";
    private Storage storage;
    private TaskList tasks;
    private Ui ui;
    private AliasList aliases;
    private boolean isExit;

    public Lux() {
        this(DEFAULT_FILE_PATH);
    }

    /**
     * Instantiate a new Lux bot with the given filepath for storage
     *
     * @param filePath path to store and retrieve saved data
     */
    public Lux(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        isExit = false;
        try {
            tasks = new TaskList(storage.loadTasks());
            aliases = storage.loadAliases();
        } catch (LuxException e) {
            ui.showLoadingError();
            tasks = new TaskList();
            aliases = new AliasList();
        }
    }

    /**
     * Runs the console application loop. This method prints a welcome
     * message and then reads user input until a command that indicates exit
     * is executed.
     */
    public void run() {
        System.out.println(ui.showWelcome());
        while (!isExit) {
            try {
                String fullCommand = ui.readCommand();
                System.out.println(ui.showLine());
                Command c = Parser.parse(fullCommand, aliases);
                System.out.println(c.execute(tasks, ui, storage, aliases));
                isExit = c.isExit();
            } catch (LuxException e) {
                System.err.println(e.getMessage());
            } finally {
                System.out.println(ui.showLine());
            }
        }
    }

    /**
     * Parse the provided input and return the response message generated by
     * the executed command. This is used by the GUI frontend to obtain a
     * single-turn response without running the interactive loop.
     *
     * @param input raw user input string
     * @return response message to display to the user (or an error message)
     */
    public String getResponse(String input) {
        try {
            Command c = Parser.parse(input, aliases);
            String message = c.execute(tasks, ui, storage, aliases);
            System.out.println(ui.showLine());
            System.out.println(message);
            isExit = c.isExit();
            return message;
        } catch (LuxException e) {
            System.err.println(e.getMessage());
            return e.getMessage();
        } finally {
            System.out.println(ui.showLine());
        }
    }

    /**
     * Return the bot's welcome message. This forwards to {@link Ui}.
     *
     * @return welcome message string
     */
    public String showWelcome() {
        return ui.showWelcome();
    }

    /**
     * Return the exit status of Lux
     *
     * @return
     */
    public boolean isExit() {
        return isExit;
    }

    public static void main(String[] args) {
        new Lux(DEFAULT_FILE_PATH).run();
    }
}
