package jordan;

import jordan.tasks.TaskList;
import jordan.ui.Ui;
import jordan.utilities.Parser;
import jordan.utilities.Storage;

import java.util.Scanner;

/**
 * The main class for the Jordan application.
 * Handles initialization, user interaction, and command parsing.
 */
public class Jordan {
    /** Default file path for storing tasks. */
    private static final String FILE_PATH = "./data/jordan.txt";
    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;

    /**
     * Constructs a Jordan instance with a specified file path.
     *
     * @param filePath The path to the storage file.
     */
    public Jordan(String filePath) {
        this.storage = new Storage(filePath);
        this.ui = new Ui();
        try {
            this.tasks = new TaskList(this.storage.load());
        } catch (JordanException e) {
            ui.printError(e);
            tasks = new TaskList();
        }
    }

    /**
     * Constructs a Jordan instance with the default file path.
     */
    public Jordan() {
        this(FILE_PATH);
    }

    /**
     * Processes a user prompt and returns the application's response.
     *
     * @param userPrompt The user's input command.
     * @return The response generated by the application.
     */
    public String getResponse(String userPrompt) {
        try {
            String response = Parser.parse(ui, tasks, userPrompt);
            assert response != null : "Response cannot be null";
            storage.save(tasks);
            return response;
        } catch (JordanException e) {
            return ui.printError(e);
        }
    }

    /**
     * Returns the UI instance used by the application.
     *
     * @return The Ui object.
     */
    public Ui getUi() {
        return this.ui;
    }

    /**
     * Runs the main application loop, handling user input and commands.
     */
    public void run() {
        Scanner scanner = new Scanner(System.in);
        boolean isExitProgram = false;
        while (!isExitProgram) {
            ui.promptUserAddTask();
            String phrase = scanner.nextLine();
            try {
                Parser.parse(ui, tasks, phrase);
                storage.save(tasks);
                isExitProgram = Parser.isExit();
            } catch (JordanException e) {
                ui.printError(e);
            }
        }
    }

    /**
     * The main entry point for the application.
     *
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) {
        new Jordan("data/jordan.txt").run();
    }
}
