package clam;

import command.Command;
import parser.Parser;
import storage.Storage;
import ui.Ui;
import task.TaskList;

import java.io.FileNotFoundException;
import java.util.Objects;

/**
 * The main class for the Clam.Clam chatbot program, which consists of the {@link TaskList} task list,,
 * {@link Storage} save file I/O and {@link Ui} user interface.
 * <p>
 * This class initialises all components upon construction, and its {@code main()} method
 * starts the program, with the filepath defined to be "./save.txt".
 * </p>
 */
public class Clam {
    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;

    /**
     * Constructs a {@link Clam} object with the specified filepath.
     * <p>
     * If no file is found at the specified filepath, it will create a new
     * file at the specified filepath to work with.
     * </p>
     * @param filepath the filepath for the .txt file that this {@code Clam.Clam}
     *                 object will run the program with.
     */
    public Clam(String filepath) {
        storage = new Storage(filepath);
        ui = new Ui();
    }

    /**
     * Returns the string text to be printed upon initialisation of the Clam GUI,
     * which includes any error messages in regards to the loading of the save file.
     *
     * @return greeting string and relevant error message(s), if any
     */
    public String init() {
        StringBuilder sb = new StringBuilder();
        sb.append("Hi! I'm Clam, your personal task manager :)");
        try {
            tasks = storage.loadSaveFile();
        } catch (FileNotFoundException e) {
            tasks = new TaskList();
            sb.append("\nIt seems there's an error with loading the save file :(");
        } catch (Exception e) {
            tasks = new TaskList();
            sb.append("\n").append(e.getMessage());
        }

        assert !Objects.isNull(tasks);
        return sb.toString();
    }

    /**
     * A function that facilitates the I/O of the user input and chatbot response output for the GUI,
     * retrieving the string from the {@link Ui} object and providing it to the GUI for display.
     *
     * @param input the user input from the GUI
     * @return the corresponding output that is generated by Clam
     */
    public String getResponse(String input) {
        try {
            Command c = Parser.parse(input);
            c.execute(tasks, ui, storage);
            return ui.printToGui();
        } catch (Exception e) {
            return e.getMessage();
        }
    }
}
