package xenon;

import java.io.IOException;

import xenon.command.Command;
import xenon.exception.XenonException;
import xenon.parser.Parser;
import xenon.storage.Storage;
import xenon.tasklist.TaskList;

/**
 * Represents a chatbot in the application.
 */
public class Xenon {

    private TaskList tasks;
    private Storage storage;
    private String commandType;

    /**
     * Constructs a new instance of the Xenon chatbot.
     * Initialises the user interface, storage system, and loads any existing tasks
     * from the specified file path.
     *
     * @param filePath The file path where the task data is stored. This file
     *                 will be used to load existing tasks and persist new ones.
     */
    public Xenon(String filePath) {
        storage = new Storage(filePath);
        try {
            this.tasks = new TaskList(storage.loadData(filePath));
        } catch (IOException e) {
            System.out.println("Unable to load data");
        }
    }

    /**
     * Generates a response based on the user input.
     * The input is parsed to determine the appropriate command, which is then executed.
     * If an exception occurs during execution, an error message is returned.
     *
     * @param input The user's input as a string.
     * @return A string containing the response generated by executing the command
     *         or an error message if any exception occurs during command execution.
     */
    public String getResponse(String input) {
        try {
            Command c = Parser.parse(input);
            commandType = c.getClass().getSimpleName();
            return c.execute(this.tasks, this.storage);
        } catch (XenonException error) {
            commandType = "Error";
            return error + "\n"
                    + "If you are unsure of how to use me, type 'help' to see a list of available commands";
        }

    }

    public String getCommandType() {
        return commandType;
    }
}
