package johnny.exception;

/**
 * Exception class for any exceptions generated by Johnny
 */
public class JohnnyException extends Exception {
    /**
     * Creates a new JohnnyException with a specified message.
     * 
     * @param message Message to be output when a JohnnyException is caught
     */
    public JohnnyException(String message) {
        super(message);
    }
}
