package command;

import exception.GenieweenieException;
import storage.Storage;
import task.TaskList;
import ui.Ui;

/**
 * Represents a user command.
 */
public abstract class Command {

    protected String response; // stores the output of the command

    /**
     * Executes the command.
     *
     * @param tasks the TaskList
     * @param ui the UI
     * @param storage the storage handler
     * @throws GenieweenieException if execution fails
     */
    public abstract String execute(TaskList tasks, Ui ui, Storage storage) throws GenieweenieException;

    /**
     * Checks if command is an exit command.
     *
     * @return true if exit command
     */
    public boolean isExit() {
        return false;
    }

    // Retrieves the response generated by execute
    public String getResponse() {
        return response;
    }
}
