package storage;

import task.*;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 * A utility class for loading and writing data to a save file.
 * <p>
 * The task list data is saved in a plaintext format on a .txt file
 * in a default filepath.
 * </p>
 */
public class Storage {
    private final String filepath;

    /**
     * Constructs a {@link Storage} object with a specified filepath.
     *
     * @param filepath the filepath for the .txt file that this {@code Storage}
     *                 object will read and write from
     */
    public Storage(String filepath) {
        this.filepath = filepath;
    }

    /**
     * Loads the plaintext data from the file at the specified filepath.
     * <p>
     * Returns an empty {@link TaskList} if the file at the specified filepath
     * does not exist. Otherwise, the save file will be read line by line,
     * each line corresponding to one task, and added to the {@link TaskList}.
     * The {@link TaskList} will be returned when all lines in the save file
     * have been read.
     * </p>
     * <p>
     * If any lines of the save file cannot be loaded properly, the line will
     * be added to an error stack and thrown with an exception.
     * </p>
     * @return a {@link TaskList} object with the corresponding tasks based
     * on the save file
     * @throws Exception if an error occurs while reading the save file
     */
    public TaskList loadSaveFile() throws Exception {
        File f = new File(filepath);
        TaskList tasks = new TaskList();
        if (f.exists()) {
            Scanner s = new Scanner(f);
            boolean error = false;
            StringBuilder errorStack = new StringBuilder();
            while (s.hasNext()) {
                try {
                    tasks.loadTask(s.nextLine());
                } catch (Exception e) {
                    error = true;
                    errorStack.append(e.getMessage()).append("\n");
                }
            }
            if (error) throw new Exception(errorStack.toString());
        }
        return tasks;
    }

    /**
     * Saves the task list data to the plaintext file at the specified filepath.
     *<p>
     * The save file text is generated by writing one line per task in the {@link TaskList},
     * with key data separated by the character "|" in a delimited fashion. The first value
     * is the task type ({@code todo}/{@code deadline}/{@code event}), the second value is whether that task is marked
     * or unmarked (denoted in binary fashion, {@code 0}/{@code 1}), the third value is the description (i.e
     * the title of the task), and subsequent values represent extra information for {@code deadline}
     * and {@code event} objects.
     * </p>
     * @param tasklist the task list to save to the file at the specified filepath
     * @throws IOException if an error occurs with while attempting to write to the file
     */
    public void saveToFile(TaskList tasklist) throws IOException {
        StringBuilder sb = new StringBuilder();
        for (Task i : tasklist.tasks) {
            if (i instanceof ToDo td) {
                sb.append("todo|").append(td.isDone ? "1|" : "0|").append(td.description).append(System.lineSeparator());
            } else if (i instanceof Deadline dl) {
                sb.append("deadline|").append(dl.isDone ? "1|" : "0|").append(dl.description).append("|").append(dl.deadline)
                        .append(System.lineSeparator());
            } else if (i instanceof Event ev) {
                sb.append("event|").append(ev.isDone ? "1|" : "0|").append(ev.description).append("|").append(ev.from)
                        .append("|").append(ev.to).append(System.lineSeparator());
            }
        }
        File f = new File("./save.txt");
        FileWriter fw = new FileWriter(f);
        fw.write(sb.toString());
        fw.close();
    }
}
