package toodoo.parser;

import toodoo.exceptions.DateTimeConflictException;
import toodoo.exceptions.EmptyDeadlineException;
import toodoo.exceptions.EmptyDescriptionException;
import toodoo.exceptions.EmptyFromException;
import toodoo.exceptions.EmptyIndexException;
import toodoo.exceptions.EmptyRegexException;
import toodoo.exceptions.EmptyTaskListException;
import toodoo.exceptions.EmptyToException;
import toodoo.exceptions.IndexDoesNotExistException;
import toodoo.exceptions.TaskAlreadyMarkedException;
import toodoo.exceptions.TaskAlreadyUnmarkedException;
import toodoo.exceptions.UnknownKeywordException;
import toodoo.tasklist.TaskList;

/**
 * The Parser is used by TooDoo to receive and process the input by the user.
 */
public class Parser {

    /**
     * Returns a String representing the Keyword of the user's input.
     *
     * @param userInputStrings An array containing the words in the user's input.
     * @return The keyword (first word) of the user's input.
     */
    public String getKeyWord(String[] userInputStrings) {
        return userInputStrings[0];
    }

    /**
     * Processes the user's input and returns the response string.
     *
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @param userInput The user's input string.
     * @return The response string generated by the command.
     */
    public String processUserInput(TaskList taskList, String userInput) {
        Keyword keyword;
        String[] splitUserInput = userInput.split(" ");
        String firstWord = splitUserInput[0];

        assert taskList != null : "TaskList should not be null";
        assert userInput != null : "User input should not be null";
        assert splitUserInput.length > 0 : "Input array should not be empty";

        try {
            keyword = Keyword.valueOf(firstWord.toUpperCase());
        } catch (IllegalArgumentException e) {
            keyword = Keyword.UNKNOWN;
        }

        try {
            switch (keyword) {
            case BYE:
                return "exit";
            case TODO:
            case DEADLINE:
            case EVENT:
                return processAddTask(keyword, splitUserInput, taskList);
            case DELETE:
            case FIND:
            case SORT:
            case LIST:
            case MARK:
            case UNMARK:
                return processTaskListManipuliation(keyword, splitUserInput, taskList);
            case UNKNOWN:
                throw new UnknownKeywordException(firstWord);
            default:
                throw new UnknownKeywordException(firstWord);
            }

        } catch (UnknownKeywordException | EmptyDescriptionException | EmptyDeadlineException
                | EmptyFromException | EmptyToException | EmptyRegexException | EmptyIndexException
                | DateTimeConflictException | IndexDoesNotExistException | TaskAlreadyMarkedException
                | TaskAlreadyUnmarkedException | EmptyTaskListException e) {
            return e.getMessage();
        } catch (NumberFormatException e) {
            return "Please provide a valid integer for the task number :(";
        }
    }

    /**
     * Process the user's input when it is related to task list manipulation.
     *
     * @param keyword The keyword that triggers a response from TooDoo.
     * @param splitUserInput An array containing the words in the user's input.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @return The response string generated by the task list manipulation command.
     * @throws EmptyIndexException If the index to be marked is not specified.
     * @throws IndexDoesNotExistException If the index is out of bounds of the taskList.
     * @throws TaskAlreadyMarkedException If the task specified is already done.
     * @throws TaskAlreadyUnmarkedException If the task specified is already marked as not done.
     * @throws EmptyRegexException If the regex to find is not specified.
     * @throws EmptyTaskListException If the task list is empty.
     * @throws UnknownKeywordException If the keyword is not recognised.
     */
    public String processTaskListManipuliation(Keyword keyword, String[] splitUserInput, TaskList taskList)
            throws EmptyIndexException, IndexDoesNotExistException, TaskAlreadyMarkedException,
            TaskAlreadyUnmarkedException, EmptyRegexException, EmptyTaskListException, UnknownKeywordException {
        switch(keyword) {
        case MARK:
            return TaskListManipulationProcessor.handleMark(splitUserInput, taskList);
        case UNMARK:
            return TaskListManipulationProcessor.handleUnmark(splitUserInput, taskList);
        case DELETE:
            return TaskListManipulationProcessor.handleDelete(splitUserInput, taskList);
        case FIND:
            return TaskListManipulationProcessor.handleFind(splitUserInput, taskList);
        case SORT:
            return taskList.sortTasks();
        case LIST:
            return taskList.toString();
        default:
            throw new UnknownKeywordException(splitUserInput[0]);
        }
    }

    /**
     * Process the user's input when it is related to task adding.
     *
     * @param keyword The keyword that triggers a response from TooDoo.
     * @param splitUserInput An array containing the words in the user's input.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @return The response string generated by the task adding command.
     * @throws EmptyDescriptionException If the description of the task is an empty string.
     * @throws EmptyFromException If the from time of the Event is an empty string.
     * @throws EmptyToException If the to time of the Event is an empty string.
     * @throws EmptyDeadlineException If the deadline of the Deadline is an empty string.
     * @throws DateTimeConflictException If the to time is before the from time.
     * @throws UnknownKeywordException If the keyword is not recognised.
     */
    public String processAddTask(Keyword keyword, String[] splitUserInput, TaskList taskList)
            throws EmptyDescriptionException, EmptyFromException, EmptyToException, EmptyDeadlineException,
            DateTimeConflictException, UnknownKeywordException {
        switch (keyword) {
        case TODO:
            String processedToDoString = ToDoProcessor.processToDoString(splitUserInput);

            assert processedToDoString != null : "Processed ToDo string should not be null";

            return taskList.addToDo(processedToDoString);
        case DEADLINE:
            String[] processedDeadlineString = DeadlineProcessor.processDeadlineString(splitUserInput);

            assert processedDeadlineString.length == 2 : "Deadline should return 2 elements";

            return taskList.addDeadline(processedDeadlineString[0], processedDeadlineString[1]);
        case EVENT:
            String[] processedEventString = EventProcessor.processEventString(splitUserInput);

            assert processedEventString.length == 3 : "Event should return 3 elements";

            return taskList.addEvent(processedEventString[0], processedEventString[1], processedEventString[2]);
        default:
            throw new UnknownKeywordException(splitUserInput[0]);
        }
    }
}
