package gloqi.ui;

import gloqi.command.Command;
import gloqi.command.CommandParser;
import gloqi.task.Deadline;
import gloqi.task.Event;
import gloqi.task.Task;
import gloqi.task.Todo;

// this Javadoc is generated by chatgpt

/**
 * Represents a chatbot that manages tasks.
 * The chatbot reads user commands, executes them, and stores tasks.
 */
public class Gloqi {

    private static final String CHATBOT_NAME = "Gloqi";
    private static final String DEFAULT_DATA_PATH = "data/data.txt";
    private final Ui ui;
    private BankList bankList;

    /**
     * Creates a new Gloqi chatbot with default data file path:data/data.txt for storing tasks.
     */
    public Gloqi() {
        this.ui = new Ui(CHATBOT_NAME);
    }

    /**
     * Initializes the task bank by loading tasks from persistent storage.
     * <p>
     * This convenience overload uses the default data file path {@value #DEFAULT_DATA_PATH}.
     * See {@link #initialize(String)} for behavior when a custom path is supplied.
     *
     * @return a success message if tasks are loaded, or an error message if loading fails
     * @see #initialize(String)
     */
    public String initialize() {
        return initialize(DEFAULT_DATA_PATH);
    }

    /**
     * Initializes the task bank by loading tasks from persistent storage.
     * <p>
     * If the data file is corrupted or cannot be read, an error message is returned
     * from the thrown {@link GloqiException}. Otherwise, confirms that tasks were
     * loaded successfully.
     *
     * @param filePath path to the data file used for loading tasks
     * @return a success message if tasks are loaded, or an error message if loading fails
     */
    public String initialize(String filePath) {
        try {
            this.bankList = new BankList(new DataManager(filePath));
            bankList = bankList.loadBankList();
        } catch (GloqiException e) {
            return e.getMessage();
        }
        return "Tasks are loaded successfully!";
    }


    /**
     * Runs the main logic of the chatbot.
     * Reads user input, parses commands, executes them, and continues
     *
     * @param userInput user input string
     * @return response String from the chatbot
     */
    public String run(String userInput) {
        try {
            CommandParser commandParser = new CommandParser(userInput);
            Command cmd = commandParser.getCmd();
            String response = executeCommand(cmd, commandParser);
            assert response != null : "response should not be null";
            return response;
        } catch (GloqiException e) {
            return e.getMessage();
        }
    }

    /**
     * Returns the greeting message of the chatbot.
     *
     * @return greeting message
     */
    public String getGreeting() {
        return ui.getGreetMessage();
    }

    /**
     * Executes the given command with its parsed arguments.
     *
     * @param cmd           the command to execute
     * @param commandParser the parser holding the command arguments
     * @return the response message after executing the command
     * @throws GloqiException if the command is invalid or arguments are incorrect
     */
    private String executeCommand(Command cmd, CommandParser commandParser) throws GloqiException {
        assert cmd != null : "cmd should not be null";
        return switch (cmd) {
        case LIST -> handleList();
        case MARK -> handleMark(commandParser);
        case UNMARK -> handleUnmark(commandParser);
        case TODO -> handleTodo(commandParser);
        case DEADLINE -> handleDeadline(commandParser);
        case EVENT -> handleEvent(commandParser);
        case DELETE -> handleDelete(commandParser);
        case SHOW -> handleShow(commandParser);
        case FIND -> handleFind(commandParser);
        case BYE -> ui.getEndMessage();
        default -> throw invalidCommand();
        };
    }

    private String handleList() {
        return bankList.printList();
    }

    private String handleMark(CommandParser parser) throws GloqiException {
        return bankList.markTask(parser.getIntArg()[0]);
    }

    private String handleUnmark(CommandParser parser) throws GloqiException {
        return bankList.unmarkTask(parser.getIntArg()[0]);
    }

    private String handleTodo(CommandParser parser) throws GloqiException {
        Task task = new Todo(parser.getStringArg()[0]);
        return bankList.addTask(task);
    }

    private String handleDeadline(CommandParser parser) throws GloqiException {
        Task task = new Deadline(parser.getStringArg());
        return bankList.addTask(task);
    }

    private String handleEvent(CommandParser parser) throws GloqiException {
        Task task = new Event(parser.getStringArg());
        return bankList.addTask(task);
    }

    private String handleDelete(CommandParser parser) throws GloqiException {
        return bankList.deleteTask(parser.getIntArg());
    }

    private String handleShow(CommandParser parser) {
        return bankList.printList(parser.getDateArg());
    }

    private String handleFind(CommandParser parser) {
        return bankList.findTask(parser.getStringArg()[0]);
    }

    private GloqiException invalidCommand() {
        return new GloqiException("""
                Invalid command, only following commands are supported:
                list, mark, unmark, bye, deadline, event, todo, show, delete, find""");
    }
}
