package toodoo;

import java.io.FileNotFoundException;

import toodoo.exceptions.StorageFormatException;
import toodoo.parser.Parser;
import toodoo.storage.Storage;
import toodoo.tasklist.TaskList;
import toodoo.ui.Ui;

/**
 * The main logic class for the TooDoo application.
 * Handles user input processing, task list management, and interaction with storage and UI.
 */
public class TooDoo {

    private Storage storage;
    private Ui ui;
    private TaskList taskList;
    private Parser parser;
    private String filePath;

    /**
     * Constructs the TooDoo chatbot by creating the Ui, Parser, Storage and TaskList object.
     * It also checks if the storage .txt file exists.
     * @param filePath The path to the storage .txt file.
     */
    public TooDoo(String filePath) {
        ui = new Ui();
        parser = new Parser();
        this.filePath = filePath;
    }

    /**
     * Processes a user input string and returns the response generated by the parser.
     *
     * @param input The user input string.
     * @return The response string generated by TooDoo.
     */
    public String getResponse(String input) {
        return parser.processUserInput(taskList, input);
    }

    /**
     * Returns the welcome message for the user.
     *
     * @return The welcome message string.
     */
    public String getWelcome() {
        return ui.getWelcome();
    }

    /**
     * Returns the exit message for the user.
     * @return The exit message string.
     */
    public String getExit() {
        return ui.getExit();
    }

    /**
     * Saves the current task list to storage.
     * @return A confirmation message after saving.
     */
    public String saveList() {
        return storage.saveList(taskList);
    }

    /**
     * Loads the task list from storage.
     * @return A message indicating the result of the load operation.
     */
    public String loadList() {
        try {
            storage = new Storage(filePath);
            taskList = new TaskList(storage.loadList());
            return "Your task list from a previous run has been successfully loaded!";
        } catch (FileNotFoundException e) {
            taskList = new TaskList();
            return "It would seem that you have no existing task list! Starting a blank one for you now :)";
        } catch (StorageFormatException e) {
            taskList = new TaskList();
            return e.getMessage();
        }
    }

}
